image: registry.gitlab.ea.com/dre/automation/frostbite/framework-linux:7.19.01

before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ea.com/foundation/foundation-ci-files.git ci-files

debug:
    script:
        - mono $FRAMEWORK_HOME/bin/nant.exe -masterconfigfile:ci-files/dev.xml -buildroot:/br -D:config=unix64-clang-dev-debug test-run
debug-opt:
    script:
        - mono $FRAMEWORK_HOME/bin/nant.exe -masterconfigfile:ci-files/dev.xml -buildroot:/br -D:config=unix64-clang-dev-debug-opt test-run
opt:
    script:
        - mono $FRAMEWORK_HOME/bin/nant.exe -masterconfigfile:ci-files/dev.xml -buildroot:/br -D:config=unix64-clang-dev-opt test-run
